set(LINKER_SCRIPT ${CMAKE_CURRENT_LIST_DIR}/linker.ld)
set(DZOS_XXD_DIR ${CMAKE_SOURCE_DIR}/xxd)
set(DZOS_KERNEL_DIR ${CMAKE_CURRENT_LIST_DIR})
set(DZOS_KERNEL_SRC_DIR ${CMAKE_CURRENT_LIST_DIR}/src)
set(DZOS_KERNEL_INC_DIR ${CMAKE_CURRENT_LIST_DIR}/include)
set(FLANTERM_SOURCES ${flanterm_SOURCE_DIR}/src/flanterm.c ${flanterm_SOURCE_DIR}/src/flanterm_backends/fb.c)

file(GLOB_RECURSE KERNEL_C_SOURCES ${CMAKE_CURRENT_LIST_DIR}/src/*.c)
file(GLOB_RECURSE KERNEL_ASM_SOURCES ${CMAKE_CURRENT_LIST_DIR}/src/*.S)